#!/usr/bin/bash

LENGTH=$1

# 1 = ALPHA
# 2 = NUM
# 3 = ALPHA NUM
# 4 = ALPHA NUM SPECIAL CHAR
TYPE=$2

_help() {
  echo "Usage: $1 <length> <type>"
  echo "Types :"
  echo " 1 = ALPHA"
  echo " 2 = NUM"
  echo " 3 = ALPHA NUM"
  echo " 4 = ALPHA NUM SPECIAL CHAR"
}

if [ -z "$LENGTH" ] || [ -z "$TYPE" ]; then
  _help $0
  exit 1
fi

if [ ! $TYPE -ge 1 ] || [ ! $TYPE -le 4 ]; then
  echo "Wrong type"
  _help $0
  exit 1
fi

ALPHA="abcdefghijklmnopqrstuvwxyz"
NUM="1234567890"
SPECIAL_CHAR=",#;:!?.&(-_)=#{[@]}+$%"


DICT=""

case $TYPE in
  1)
    DICT="$ALPHA"
    ;;
  2)
    DICT="$NUM"
    ;;
  3)
    DICT="$ALPHA$NUM"
    ;;
  4)
    DICT="$ALPHA$NUM$SPECIAL_CHAR"
    ;;
esac

DICT_LENGTH=${#DICT}

password=""

i=0
while [ $i -lt $LENGTH ]; do
  i=$(($i+1))

  index=$((1 + $RANDOM % $DICT_LENGTH))

  char=$(echo "$DICT" | cut -c$index)
  
  if [ $index -le ${#ALPHA} ]; then
    case=$((1 + $RANDOM % 2))

    if [ $case -eq 1 ]; then # UPPER
      char=${char^^}
    fi
  fi

  password="$password$char"
done

echo $password
